// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqEfSDTAzdD1JkZK9KpqNokqPvzoc3fBs',
    appId: '1:870537563499:web:fe7ba71ded58ef2510902e',
    messagingSenderId: '870537563499',
    projectId: 'carrot-market-282',
    authDomain: 'carrot-market-282.firebaseapp.com',
    storageBucket: 'carrot-market-282.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3mFRyWV4cmvOb4sJHPnYYwJLLcUGThAM',
    appId: '1:870537563499:android:ad9456fd113895ca10902e',
    messagingSenderId: '870537563499',
    projectId: 'carrot-market-282',
    storageBucket: 'carrot-market-282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3LNN70rS-t53-_2-nT98uoz4ZH6bdcq8',
    appId: '1:870537563499:ios:060015facdfabbb910902e',
    messagingSenderId: '870537563499',
    projectId: 'carrot-market-282',
    storageBucket: 'carrot-market-282.appspot.com',
    iosClientId: '870537563499-qk0sc15drk658umdpvbp3gtl6l31khtm.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrotMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3LNN70rS-t53-_2-nT98uoz4ZH6bdcq8',
    appId: '1:870537563499:ios:060015facdfabbb910902e',
    messagingSenderId: '870537563499',
    projectId: 'carrot-market-282',
    storageBucket: 'carrot-market-282.appspot.com',
    iosClientId: '870537563499-qk0sc15drk658umdpvbp3gtl6l31khtm.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrotMarket',
  );
}
